apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.metadata.name }}
  labels:
    {{- include "fidelis.labels" . | nindent 4 }}

{{- with .Values.configmap.data}}
data:
  {{- toYaml . | nindent 2 }}
{{- end}}
# data:
#   teste-arquivo: {{ .Values.configmap.data.conteudo }}