apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.metadata.name }}
  # namespace: {{ .Values.configmap.metadata.namespace }}

{{- with .Values.configmap.data}}
data:
  {{- toYaml . | nindent 2 }}
{{- end}}
# data:
#   teste-arquivo: {{ .Values.configmap.data.conteudo }}